version: 0.2
phases:
  install:
    runtime-versions:
        java: corretto11
  pre_build:
    commands:
      - echo In the pre_build phase...
      - ./gradlew test
  build:
    commands:
      - echo Build completed on `date`
      - ./gradlew build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/libs/*SNAPSHOT.jar
  discard-paths: yes