# Spring properties
spring:
    application:
        name: message-service  # Service registers under this name

# HTTP Server
server.port: 2222   # HTTP (Tomcat) port
server.servlet.context-path: /api

# Enable actuator access without security checks - DEVELOPMENT ONLY
# Spring Boot 2.x
management.endpoints.web.exposure.include: '*'